# https://github.com/mqyqingfeng/Blog/issues/236

name: gitee-sync
on:
  push:
    branches:
      - main
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github organization repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/d2learn'
          dst: 'gitee/xlings-res'
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          static_list: "xlings-project-templates"
          force_update: true
          debug: true